[package]
name = "staking-nft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.14.10"
borsh = "0.9.3"
thiserror = "1.0.38"